### ISSUE TITLE
Not importing anything from sticky-events.es5.js

### ISSUE THREAD

**Issue by ryanburnette** [ryanwalters/sticky-events#1]
Are you sure sticky-events.es5.js is building correctly? I'm importing it with Webpack but getting undefined.

```javascript
var StickyEvents = require('sticky-events/sticky-events.es5.js')
console.log(StickyEvents)
=> undefined
```

Or am I doing something wrong here?

**Comment by ryanburnette** [comment]
I was planning to anyway... so I just set up babel to transpile the project myself and included the es6. I don't think the es5 output is working for some reason though. Might do a PR and try to fix it if I have time.

**Comment by ryanwalters** [comment]
Thanks for catching this! [v1.2.1](https://github.com/ryanwalters/sticky-events/tree/v1.2.1) should hopefully fix the issue.

**Comment by ryanburnette** [comment]
1.2.1 fixed it
