### ISSUE TITLE
Event bubbling

### ISSUE THREAD

**Issue by sntran** [ryanwalters/sticky-events#14]
Is there any performance hit or issue if we bubble the sticky events? I would like to use a single event handler for those events, since `event.target` already gives me the sticky element.

**Comment by ryanwalters** [comment]
Just so I understand correctly, are you looking for events to be emitted at the instance level rather than attaching event listeners to individual sticky elements?

Something along these lines:
```js
const stickyEvents = new StickyEvents();

stickyEvents.on(StickyEvents.CHANGE, (stickyElement, isSticky) => {
  stickyElement.classList.toggle('highlighted', isSticky);
});
```

**Comment by sntran** [comment]
Sorry, I meant bubbling the event in https://github.com/ryanwalters/sticky-events/blob/83779d4b15c4229876d2effe7c4c1c931a6ed827/sticky-events.js#L216-L217 by changing to:

```js
new CustomEvent(StickyEvent.CHANGE, { detail: { isSticky }, bubbles: true })
```

When the event is bubble up, instead of

```js
const { stickyElements } = stickyEvents;

stickyElements.forEach(sticky => {
  sticky.addEventListener(StickyEvents.CHANGE, (event) => {
    sticky.classList.toggle('bg-dark', event.detail.isSticky);
  });
});
```

I can do:

```js
document.addEventListener(StickyEvents.CHANGE, `.custom-sticky-selector`, (event) => {
  const sticky = event.target;
  sticky.classList.toggle('bg-dark', event.detail.isSticky);
});
```

**Comment by ryanwalters** [comment]
Ah, gotcha. I don't see any issues with implementing that. I'll add this to the next 2.x release.

**Comment by ryanwalters** [comment]
Event bubbling added to 2.4.0.
