### ISSUE TITLE
Support for Shadow DOM 

### ISSUE THREAD

**Issue by TomTomB** [ryanwalters/sticky-events#20]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for sticky events inside Shadow DOM. 

**Describe alternatives you've considered**
I´ve tried working around this issue with the following snippet:
```ts
const shadowRoot = document.querySelector('my-element').shadowRoot;

const stickyEvents = new StickyEvents({
      container: shadowRoot.querySelector('#wrapper'),
      enabled: false
});

const stickies = shadowRoot.querySelectorAll('.category-header');

stickyEvents.addStickies(stickies);
stickyEvents.enableEvents();
```

This ends up with the following error message:
```
Cannot read property 'observe' of undefined
```

Update:

I´ve got it working using the following snippet:

```ts
const shadowRoot = document.querySelector('my-element').shadowRoot;

const stickyEvents = new StickyEvents({
     container: shadowRoot.querySelector('#wrapper'),
     stickySelector: '.category-header',
     enabled: true
});

const stickies = shadowRoot.querySelectorAll('.category-header');
stickyEvents.addStickies(stickies);
```
Manually adding the sticky elements is needed, since the initial selection via prop `stickySelector` will fail. That´s because it is selecting inside `document` and not the provided `container`.

**Comment by ryanwalters** [comment]
Fixed by #21. Thanks for this!
