### ISSUE TITLE
Can't read property top of null

### ISSUE THREAD

**Issue by ryanburnette** [ryanwalters/sticky-events#3]
I'm getting a lot of can't read property top/height of null errors.

demo: https://codepen.io/ryanburnette/pen/gerKQP

![screen shot 2018-03-15 at 12 32 19 am](https://user-images.githubusercontent.com/2252601/37444521-6aca2ccc-27e8-11e8-9546-f5520ffadc0c.png)

I was originally setting up the issue to show that if an element is pushed down by content above it the events fire as if the element were positioned where it would be if that "pushing" content were not there. If it were working you could test that by adding and removing paragraphs of content above the box.

**Comment by ryanwalters** [comment]
There seems to be an issue with IntersectionObservers in iframes. https://github.com/w3c/IntersectionObserver/issues/183

**Comment by ryanwalters** [comment]
@ryanburnette As a side note, v1.3.1 should fix your "original" issue (unrelated to the `null` errors) where the sticky element was sticking at the wrong time when there was content above the sticky element. Thanks for pointing these out!
