### ISSUE TITLE
Having issues if sticky isn't set to top: 0

### ISSUE THREAD

**Issue by argyleink** [ryanwalters/sticky-events#4]
The sentinel created for my sticky node only triggers stuck when it leaves the screen, like it's only watching top 0. My sticky element, and all of my other ones too, dont use top 0px. Makes my sticky event feel very "late," since my elements have stuck before the event fires. 

Is there a way for me to inform the sentinel of the top/bottom offset value to watch for the sticky event?

**Comment by ryanwalters** [comment]
v1.3.3 should fix this issue. Thanks for reporting!
