### ISSUE TITLE
Not triggered on some browsers

### ISSUE THREAD

**Issue by dirkluijk** [ryanwalters/sticky-events#6]
I tried to use this code in my Angular project. I created a beautiful directive for it, but I have some issues.

**Code example**
https://stuck-directive.stackblitz.io (preview)
https://stackblitz.com/edit/stuck-directive (code)

**Problem**
On Chrome, it is only triggered when scrolling fast. On Safari, it is not triggered.

**Expected**
When scrolling, the green block should become red.

**Comment by dirkluijk** [comment]
I found that on Chrome, this was the fix:

Changing:
```javascript
if (boundingClientRect.bottom >= rootBounds.top && boundingClientRect.bottom < rootBounds.bottom) {
  fire(false, stickyTarget);
}
else if (boundingClientRect.bottom < rootBounds.top) {
  fire(true, stickyTarget);
}
```
to:
```
if (boundingClientRect.bottom > rootBounds.top && boundingClientRect.bottom < rootBounds.bottom) {
  fire(false, stickyTarget);
}
else if (boundingClientRect.bottom <= rootBounds.top) {
  fire(true, stickyTarget);
}
```
fixed the issue. If you agree on this, I'll add a PR for it.

**Comment by ryanwalters** [comment]
Looks good to me, go ahead an open a PR. Thanks!

As for Safari, which [does not currently support](https://bugs.webkit.org/show_bug.cgi?id=159475) `IntersectionObserver`, please be sure to include a polyfill.

I use Polyfill.io on the demo page:
```
https://cdn.polyfill.io/v2/polyfill.min.js?features=IntersectionObserver
```
