### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by dirkluijk** [ryanwalters/sticky-events#7]
**Code example**
https://stackblitz.com/edit/stuck-directive (code + preview)

**Problem**
As you can see, in the StackBlitz preview pane, I have JavaScript issues (I think due to CORS). 

**Question**
Is there a workaround? Maybe we can fallback to a rect(0, 0, 0, 0)? Otherwise, I expect it to _silently_ fail instead of console errors.

**Comment by ryanwalters** [comment]
There seems to be an issue with `IntersectionObserver` in iframes. #3 has the link to the W3C issue.

I will add a warning to the console when trying to initialize within an iframe rather than show the error messages.
