### ISSUE TITLE
IE 11 issues

### ISSUE THREAD

**Issue by dirkluijk** [ryanwalters/sticky-events#8]
Hi,

I got some errors when running this script on IE11. I know `position: sticky` does not event work on IE11, but this script should therefore _silently_ fail.

Two errors:
- IE11 does not work well with ES6. This can be fixed in `package.json`:
```json
{
  "main": "sticky-events.es5.js",
  "es2015": "sticky-events.js"
}
```
- IE11 does not support `new CustomEvent()`. Is there a way to disable the "sticky-events" script on IE11?

**Comment by ryanwalters** [comment]
As stated in the Readme, IE11 is not supported.

You could use something like Modernizr to detect `CustomEvent` or roll your own with something like:

```js
if (typeof CustomEvent === 'function') {
    // Do sticky-events stuff
}
```

**Comment by dirkluijk** [comment]
The problem is that in my Angular app, when I have:

```typescript

import { observeStickyEvents } from 'sticky-events';

class MyComponent {
  ngOnInit(): {
    observeStickyEvents();
  }
}
```

this still fails due to loading `sticky-events.js` from node_modules instead of `sticky-events.es5.js`.

**Comment by ryanwalters** [comment]
What happens if you `import { observeStickyEvents } from 'sticky-events/sticky-events.es5'`?

I plan on exporting the ES5 version by default in 2.0.
